"""empty message

Revision ID: d3855c994820
Revises: 08b7edb7e419
Create Date: 2020-11-20 00:27:18.001120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3855c994820'
down_revision = '08b7edb7e419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'upcoming_shows_count')
    op.drop_column('venue', 'past_shows_count')
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'past_shows_count')
    # ### end Alembic commands ###
